; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "Clinic Management"
#define MyAppVersion "1.0"
#define MyAppPublisher "Mohammad Sayd"
#define MyAppExeName "Program Clinic Management.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{AA09B5E5-FC91-4C4E-A60E-D3A17C429ABF}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
DisableProgramGroupPage=yes

//النص الترحيبي
InfoAfterFile=C:\Users\syrian technology\Desktop\My Project\مشروع تخرج Mohammad\ملفات\وصف شاشة ترحيبية للتثبيت.txt
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=C:\Users\syrian technology\Desktop
OutputBaseFilename=Clinic Management Setup
// أيقونة البرنامج
SetupIconFile=C:\Users\syrian technology\Desktop\My Project\مشروع تخرج Mohammad\صور تصميم\Icon\Clinic.ico
SolidCompression=yes
WizardStyle=modern dynamic
// منع المستخدم من اختيار مسار التثبيت
DisableDirPage=yes


[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "arabic"; MessagesFile: "compiler:Languages\Arabic.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked



[Files]
// ملف التثبيت
Source: "C:\Users\syrian technology\Desktop\My Project\مشروع تخرج Mohammad\Program Clinic Management\Program Clinic Management\bin\Release\{#MyAppExeName}";DestDir: "{app}"; Flags: ignoreversion
// Database
Source: "C:\Users\syrian technology\Desktop\My Project\مشروع تخرج Mohammad\Program Clinic Management\Program Clinic Management\bin\Release\ClinicSystemDB.mdf";DestDir: "{userdocs}\Clinic Management\Database"; Flags: onlyifdoesntexist
Source: "C:\Users\syrian technology\Desktop\My Project\مشروع تخرج Mohammad\Program Clinic Management\Program Clinic Management\bin\Release\ClinicSystemDB_log.ldf";DestDir: "{userdocs}\Clinic Management\Database"; Flags: onlyifdoesntexist

// LocalDB  ملف
Source: "C:\Users\syrian technology\Desktop\My Project\مشروع تخرج Mohammad\ملفات\SqlLocalDB.msi";DestDir: "{app}\Local"; Flags: ignoreversion


; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"


[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

 
 
 
 
 
 
 
 
 
 
 
 ; ============================================================
; ===============  فحص وتثبيت LocalDB2025 ====================
; ============================================================
[Code]

// 1) فحص وجود الإنستانس LocalDB2025
function IsLocalDB2025Installed(): Boolean;
var
  ResultCode: Integer;
begin
  Result := Exec(
    'sqllocaldb',
    'info LocalDB2025',
    '',
    SW_HIDE,
    ewWaitUntilTerminated,
    ResultCode
  ) and (ResultCode = 0);
end;

// 2) تشغيل ملف LocalDB للمستخدم عبر msiexec (مضمون 100%)
procedure InstallLocalDB2025();
var
  ResultCode: Integer;
begin
  MsgBox('يرجى إكمال تثبيت LocalDB 2025 في النافذة التي ستظهر الآن، ثم اضغط "Finish" عند الانتهاء.', mbInformation, MB_OK);

  Exec(
    'msiexec.exe',
    '/i "' + ExpandConstant('{app}\Local\SqlLocalDB.msi') + '"',
    '',
    SW_SHOW,
    ewWaitUntilTerminated,
    ResultCode
  );
end;

// 3) تنفيذ الفحص بعد انتهاء التثبيت بالكامل
procedure CurStepChanged(CurStep: TSetupStep);
var
  UserChoice: Integer;
begin
  if CurStep = ssPostInstall then
  begin
    if not IsLocalDB2025Installed() then
    begin
      UserChoice := MsgBox(
        'أحد المكوّنات الضرورية (SQL Server LocalDB 2025) غير موجود على جهازك.'#13#13 +
        'سيتم الآن فتح نافذة لتثبيت الأداة المطلوبة.'#13#13 +
        'هل تريد المتابعة؟',
        mbConfirmation, MB_YESNO);

      if UserChoice = IDNO then
      begin
        MsgBox('تعذّر متابعة التثبيت بسبب نقص أحد المكوّنات الأساسية اللازمة لتشغيل البرنامج.',
               mbError, MB_OK);
        Exit;
      end;

      InstallLocalDB2025();
    end;
  end;
end;

 
 
 
 
 
 
 
 
 
 